
# Example command:
#   Humble on a NVIDIA system:
#   docker compose run gpu
#   without discrete graphics:
#   docker compose -f <nombre_archivo> run cpu

services:
    cpu:
      image: moveit/moveit2:main-humble-tutorial-source
      container_name: moveit2_tutorial_cpu
      privileged: true
      network_mode: host
      command: /bin/bash
      volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - $XAUTHORITY:/root/.Xauthority
      environment:
        QT_X11_NO_MITSHM: 1
        DISPLAY: $DISPLAY
    gpu:
      image: moveit/moveit2:main-humble-tutorial-source
      container_name: moveit2_tutorial_gpu
      privileged: true
      network_mode: host
      command: /bin/bash
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
      volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - $XAUTHORITY:/root/.Xauthority
      environment:
        QT_X11_NO_MITSHM: 1
        DISPLAY: $DISPLAY
        NVIDIA_VISIBLE_DEVICES: all
        NVIDIA_DRIVER_CAPABILITIES: all
  